version: 0.2

phases:
  install:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build
      - dotnet publish -c Release -o output
artifacts:
  files:
    - '**/*'
  base-directory: output
