name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show current working directory
        run: pwd  # 显示当前工作目录

      - name: List files in the current directory
        run: ls -la  # 列出当前目录的文件和文件夹

      - name: Navigate to frontend directory and list files
        run: |
          cd frontend
          ls -la  # 列出frontend目录中的文件

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build Angular app
        run: |
          cd frontend
          npm run build

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Show current working directory
        run: pwd  # 显示当前工作目录

      - name: List files in the current directory
        run: ls -la  # 列出当前目录的文件和文件夹

      - name: Navigate to backend directory and list files
        run: |
          cd backend
          ls -la  # 列出backend目录中的文件

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: |
          cd backend
          dotnet restore

      - name: Build .NET Core app
        run: |
          cd backend
          dotnet build --configuration Release
